export interface AIActivity {
    text: string;
    type: 'indoor' | 'outdoor' | 'both';
}

export const AI_ACTIVITIES: Record<string, AIActivity[]> = {
    'A': [
        { text: 'Aquarium', type: 'indoor' },
        { text: 'Abendessen', type: 'both' },
        { text: 'Alpaka-Wanderung', type: 'outdoor' },
        { text: 'Atelierbesuch', type: 'indoor' },
        { text: 'Achterbahn', type: 'outdoor' },
        { text: 'Ausflug', type: 'outdoor' },
        { text: 'Angeln', type: 'outdoor' },
        { text: 'Aperitif', type: 'both' },
        { text: 'Autokino', type: 'outdoor' },
        { text: 'Ausstellung', type: 'indoor' }
    ],
    'B': [
        { text: 'Bowling', type: 'indoor' },
        { text: 'Baden', type: 'both' },
        { text: 'Brunch', type: 'both' },
        { text: 'Billard', type: 'indoor' },
        { text: 'Bergsteigen', type: 'outdoor' },
        { text: 'Bootsfahrt', type: 'outdoor' },
        { text: 'Barbesuch', type: 'indoor' },
        { text: 'Backen', type: 'indoor' },
        { text: 'Beachvolleyball', type: 'outdoor' },
        { text: 'Biergarten', type: 'outdoor' }
    ],
    'C': [
        { text: 'Cocktails', type: 'indoor' },
        { text: 'Camping', type: 'outdoor' },
        { text: 'Casino', type: 'indoor' },
        { text: 'Canyoning', type: 'outdoor' },
        { text: 'Chillen', type: 'both' },
        { text: 'Curry-Kochen', type: 'indoor' },
        { text: 'Comedy-Show', type: 'indoor' },
        { text: 'Café-Besuch', type: 'both' },
        { text: 'Clubbing', type: 'indoor' },
        { text: 'Crossfit', type: 'both' }
    ],
    'D': [
        { text: 'Dinner', type: 'indoor' },
        { text: 'Dart', type: 'indoor' },
        { text: 'Dampferfahrt', type: 'outdoor' },
        { text: 'Drachensteigen', type: 'outdoor' },
        { text: 'Disco', type: 'indoor' },
        { text: 'Döner-Date', type: 'both' },
        { text: 'Draisinenfahrt', type: 'outdoor' },
        { text: 'Dschungeltour', type: 'outdoor' },
        { text: 'Degustation', type: 'indoor' },
        { text: 'Doko-Abend', type: 'indoor' }
    ],
    'E': [
        { text: 'Eislaufen', type: 'both' },
        { text: 'Eisessen', type: 'both' },
        { text: 'E-Bike-Tour', type: 'outdoor' },
        { text: 'Erdbeerpflücken', type: 'outdoor' },
        { text: 'Escape-Room', type: 'indoor' },
        { text: 'Einkaufsbummel', type: 'both' },
        { text: 'E-Kart', type: 'indoor' },
        { text: 'Entspannung', type: 'indoor' },
        { text: 'E-Sport', type: 'indoor' },
        { text: 'Elefantenreiten', type: 'outdoor' }
    ],
    'F': [
        { text: 'Fondue', type: 'indoor' },
        { text: 'Flohmarkt', type: 'outdoor' },
        { text: 'Fahrradtour', type: 'outdoor' },
        { text: 'Freiluftkino', type: 'outdoor' },
        { text: 'Fotografieren', type: 'outdoor' },
        { text: 'Frühstück', type: 'indoor' },
        { text: 'Fackelwanderung', type: 'outdoor' },
        { text: 'Feinschmecker-Abend', type: 'indoor' },
        { text: 'Fähre-Fahren', type: 'outdoor' },
        { text: 'Fitness', type: 'both' }
    ],
    'G': [
        { text: 'Grillen', type: 'outdoor' },
        { text: 'Golf', type: 'outdoor' },
        { text: 'Go-Kart', type: 'indoor' },
        { text: 'Galeriebesuch', type: 'indoor' },
        { text: 'Geocaching', type: 'outdoor' },
        { text: 'Gärtnern', type: 'outdoor' },
        { text: 'Gin-Tasting', type: 'indoor' },
        { text: 'Gitarre-Spielen', type: 'indoor' },
        { text: 'Gourmet-Essen', type: 'indoor' },
        { text: 'Glühwein', type: 'outdoor' }
    ],
    'H': [
        { text: 'Hubschrauberflug', type: 'outdoor' },
        { text: 'Hüttenabend', type: 'indoor' },
        { text: 'Hochseilgarten', type: 'outdoor' },
        { text: 'Hamam', type: 'indoor' },
        { text: 'Hunde-Gassi', type: 'outdoor' },
        { text: 'Hafenrundfahrt', type: 'outdoor' },
        { text: 'Heißluftballon', type: 'outdoor' },
        { text: 'Hausbar-Abend', type: 'indoor' },
        { text: 'Hotelübernachtung', type: 'indoor' },
        { text: 'Handwerken', type: 'indoor' }
    ],
    'I': [
        { text: 'Indoor-Skydiving', type: 'indoor' },
        { text: 'Iglu-Bau', type: 'outdoor' },
        { text: 'Inlineskaten', type: 'outdoor' },
        { text: 'Improtheater', type: 'indoor' },
        { text: 'Inseltour', type: 'outdoor' },
        { text: 'Indoor-Minigolf', type: 'indoor' },
        { text: 'Island-Pferde', type: 'outdoor' },
        { text: 'Indisch-Kochen', type: 'indoor' },
        { text: 'Iitalien-Abend', type: 'indoor' },
        { text: 'Intervalltraining', type: 'both' }
    ],
    'J': [
        { text: 'Jazz-Abend', type: 'indoor' },
        { text: 'Jogging', type: 'outdoor' },
        { text: 'Jahrmarkt', type: 'outdoor' },
        { text: 'Jenga', type: 'indoor' },
        { text: 'Jonglieren', type: 'both' },
        { text: 'Jollensegeln', type: 'outdoor' },
        { text: 'Jet-Ski', type: 'outdoor' },
        { text: 'Juice-Tasting', type: 'indoor' },
        { text: 'Jura-Museum', type: 'indoor' },
        { text: 'Ju-Jutsu', type: 'indoor' }
    ],
    'K': [
        { text: 'Kino', type: 'indoor' },
        { text: 'Kanufahren', type: 'outdoor' },
        { text: 'Klettern', type: 'both' },
        { text: 'Kegeln', type: 'indoor' },
        { text: 'Kochkurs', type: 'indoor' },
        { text: 'Karaoke', type: 'indoor' },
        { text: 'Kabarett', type: 'indoor' },
        { text: 'Katamaran', type: 'outdoor' },
        { text: 'Kartenspielen', type: 'indoor' },
        { text: 'Kaffee-Rösterei', type: 'indoor' }
    ],
    'L': [
        { text: 'Laser-Tag', type: 'indoor' },
        { text: 'Lagerfeuer', type: 'outdoor' },
        { text: 'Lesung', type: 'indoor' },
        { text: 'Labyrinth', type: 'outdoor' },
        { text: 'Live-Musik', type: 'indoor' },
        { text: 'Limonade-Machen', type: 'indoor' },
        { text: 'Luftballons', type: 'outdoor' },
        { text: 'Landpartie', type: 'outdoor' },
        { text: 'Lichterfest', type: 'outdoor' },
        { text: 'Longboarden', type: 'outdoor' }
    ],
    'M': [
        { text: 'Minigolf', type: 'outdoor' },
        { text: 'Museum', type: 'indoor' },
        { text: 'Massage', type: 'indoor' },
        { text: 'Musical', type: 'indoor' },
        { text: 'Malkurs', type: 'indoor' },
        { text: 'Marktbesuch', type: 'outdoor' },
        { text: 'Mountainbiking', type: 'outdoor' },
        { text: 'Mondscheinfahrt', type: 'outdoor' },
        { text: 'Marathon-Gucken', type: 'indoor' },
        { text: 'Mittelaltermarkt', type: 'outdoor' }
    ],
    'N': [
        { text: 'Nachtwanderung', type: 'outdoor' },
        { text: 'Nationalpark', type: 'outdoor' },
        { text: 'Netflix-Abend', type: 'indoor' },
        { text: 'Nordic-Walking', type: 'outdoor' },
        { text: 'Night-Shopping', type: 'indoor' },
        { text: 'Naschen', type: 'indoor' },
        { text: 'Nostalgiemarkt', type: 'outdoor' },
        { text: 'Nähkurs', type: 'indoor' },
        { text: 'Natur-Fotografie', type: 'outdoor' },
        { text: 'Ninja-Parcours', type: 'indoor' }
    ],
    'O': [
        { text: 'Oper', type: 'indoor' },
        { text: 'Oldtimer-Fahrt', type: 'outdoor' },
        { text: 'Orient-Essen', type: 'indoor' },
        { text: 'Obstpflücken', type: 'outdoor' },
        { text: 'Orgelkonzert', type: 'indoor' },
        { text: 'Outdoor-Gym', type: 'outdoor' },
        { text: 'Online-Escape', type: 'indoor' },
        { text: 'Oktoberfest', type: 'outdoor' },
        { text: 'Origami', type: 'indoor' },
        { text: 'Observation', type: 'outdoor' }
    ],
    'P': [
        { text: 'Picknick', type: 'outdoor' },
        { text: 'Planetarium', type: 'indoor' },
        { text: 'Paintball', type: 'both' },
        { text: 'Poker', type: 'indoor' },
        { text: 'Paragliding', type: 'outdoor' },
        { text: 'Puzzeln', type: 'indoor' },
        { text: 'Pferdereiten', type: 'outdoor' },
        { text: 'Paddeln', type: 'outdoor' },
        { text: 'Pilzesammeln', type: 'outdoor' },
        { text: 'Poetry-Slam', type: 'indoor' }
    ],
    'Q': [
        { text: 'Quizabend', type: 'indoor' },
        { text: 'Quiche-Backen', type: 'indoor' },
        { text: 'Quadtour', type: 'outdoor' },
        { text: 'Qualitätszeit', type: 'both' },
        { text: 'Quatschen', type: 'both' },
        { text: 'Quellenbesuch', type: 'outdoor' },
        { text: 'Quilt-Nähen', type: 'indoor' },
        { text: 'Qigong', type: 'both' },
        { text: 'Quidditch-Gucken', type: 'both' },
        { text: 'Quarantäne-Kit', type: 'indoor' }
    ],
    'R': [
        { text: 'Radtour', type: 'outdoor' },
        { text: 'Restaurant', type: 'indoor' },
        { text: 'Roadtrip', type: 'outdoor' },
        { text: 'Rudern', type: 'outdoor' },
        { text: 'Reiten', type: 'outdoor' },
        { text: 'Rätselabend', type: 'indoor' },
        { text: 'Rollschuhlaufen', type: 'both' },
        { text: 'Rooftop-Bar', type: 'both' },
        { text: 'Rodelbahn', type: 'outdoor' },
        { text: 'Reiseplanung', type: 'indoor' }
    ],
    'S': [
        { text: 'Sauna', type: 'indoor' },
        { text: 'Schwimmen', type: 'both' },
        { text: 'Stadtführung', type: 'outdoor' },
        { text: 'Sushi-Kurs', type: 'indoor' },
        { text: 'Sightseeing', type: 'outdoor' },
        { text: 'Skifahren', type: 'outdoor' },
        { text: 'Segeln', type: 'outdoor' },
        { text: 'Schlittschuhlaufen', type: 'both' },
        { text: 'Spieleabend', type: 'indoor' },
        { text: 'Surfen', type: 'outdoor' }
    ],
    'T': [
        { text: 'Theater', type: 'indoor' },
        { text: 'Therme', type: 'indoor' },
        { text: 'Tanzkurs', type: 'indoor' },
        { text: 'Tennis', type: 'both' },
        { text: 'Tierpark', type: 'outdoor' },
        { text: 'Tauchen', type: 'indoor' },
        { text: 'Trödelmarkt', type: 'outdoor' },
        { text: 'Tischtennis', type: 'both' },
        { text: 'Tee-Zeremonie', type: 'indoor' },
        { text: 'Trampolin', type: 'indoor' }
    ],
    'U': [
        { text: 'Urlaub', type: 'outdoor' },
        { text: 'U-Bahn-Tour', type: 'indoor' },
        { text: 'Uhr-Basteln', type: 'indoor' },
        { text: 'Umstyling', type: 'indoor' },
        { text: 'Unterwasserzoo', type: 'indoor' },
        { text: 'Upcycling', type: 'indoor' },
        { text: 'Urpilz-Suche', type: 'outdoor' },
        { text: 'Unihockey', type: 'indoor' },
        { text: 'Uffizien-Virtuell', type: 'indoor' },
        { text: 'Urwaldtrip', type: 'outdoor' }
    ],
    'V': [
        { text: 'Varieté', type: 'indoor' },
        { text: 'Vernissage', type: 'indoor' },
        { text: 'Videoabend', type: 'indoor' },
        { text: 'Volleyball', type: 'outdoor' },
        { text: 'Verkostung', type: 'indoor' },
        { text: 'Vogelbeobachtung', type: 'outdoor' },
        { text: 'Vesper', type: 'outdoor' },
        { text: 'Virtual-Reality', type: 'indoor' },
        { text: 'Vintage-Shopping', type: 'both' },
        { text: 'Vorspeisenabend', type: 'indoor' }
    ],
    'W': [
        { text: 'Wandern', type: 'outdoor' },
        { text: 'Wellness', type: 'indoor' },
        { text: 'Weinprobe', type: 'both' },
        { text: 'Wasserski', type: 'outdoor' },
        { text: 'Wildpark', type: 'outdoor' },
        { text: 'Wrestling', type: 'indoor' },
        { text: 'Wattwanderung', type: 'outdoor' },
        { text: 'Windsurfen', type: 'outdoor' },
        { text: 'Whisky-Tasting', type: 'indoor' },
        { text: 'Wochenendtrip', type: 'outdoor' }
    ],
    'X': [
        { text: 'Xylophon', type: 'indoor' },
        { text: 'Xbox-Nacht', type: 'indoor' },
        { text: 'XXL-Pizza', type: 'both' },
        { text: 'Xmas-Markt', type: 'outdoor' },
        { text: 'X-Wanderung', type: 'outdoor' },
        { text: 'Xylogravur', type: 'indoor' },
        { text: 'Xiaomi-Store', type: 'indoor' },
        { text: 'Xenon-Licht-Tour', type: 'outdoor' },
        { text: 'X-Crossfit', type: 'both' },
        { text: 'X-Ray-Ausstellung', type: 'indoor' }
    ],
    'Y': [
        { text: 'Yoga', type: 'both' },
        { text: 'Yacht-Trip', type: 'outdoor' },
        { text: 'YouTube-Karaoke', type: 'indoor' },
        { text: 'Yankee-Candle', type: 'indoor' },
        { text: 'Yogi-Tee', type: 'indoor' },
        { text: 'Yam-Wurzel-Essen', type: 'both' },
        { text: 'Yps-Hefte-Lesen', type: 'indoor' },
        { text: 'Yeti-Suche', type: 'outdoor' },
        { text: 'Yin-Yang-Kurs', type: 'indoor' },
        { text: 'Yoga-Retreat', type: 'both' }
    ],
    'Z': [
        { text: 'Zoo', type: 'outdoor' },
        { text: 'Zelten', type: 'outdoor' },
        { text: 'Zirkus', type: 'both' },
        { text: 'Zumba', type: 'indoor' },
        { text: 'Zaubershow', type: 'indoor' },
        { text: 'Zukunftsplanung', type: 'indoor' },
        { text: 'Zungenbrechen', type: 'indoor' },
        { text: 'Zitadelle', type: 'outdoor' },
        { text: 'Zeichenkurs', type: 'indoor' },
        { text: 'Zweiradtour', type: 'outdoor' }
    ],
    'DEFAULT': [
        { text: 'Essen', type: 'both' },
        { text: 'Spaziergang', type: 'outdoor' },
        { text: 'Kino', type: 'indoor' },
        { text: 'Spieleabend', type: 'indoor' },
        { text: 'Ausflug', type: 'outdoor' }
    ]
};
