export interface AIActivity {
    text: string;
    type: 'indoor' | 'outdoor' | 'both';
}

export const AI_ACTIVITIES: Record<string, AIActivity[]> = {
    'A': [
        { text: 'Aquarium-Besuch', type: 'indoor' },
        { text: 'Abendspaziergang im Lichterschein', type: 'outdoor' },
        { text: 'Alpaka-Wanderung', type: 'outdoor' },
        { text: 'Atelier-Abend: Gemeinsam malen', type: 'indoor' },
        { text: 'Achterbahn fahren im Freizeitpark', type: 'outdoor' },
        { text: 'Aperol Spritz Abend auf dem Balkon', type: 'both' },
        { text: 'Ausbruch aus dem Escape Room', type: 'indoor' },
        { text: 'Altstadt-Rallye', type: 'outdoor' },
        { text: 'Ayurvedische Massage für zwei', type: 'indoor' },
        { text: 'Autokino-Abend', type: 'outdoor' }
    ],
    'B': [
        { text: 'Bowling-Match', type: 'indoor' },
        { text: 'Barfusspfad erkunden', type: 'outdoor' },
        { text: 'Brunch im Lieblingscafé', type: 'both' },
        { text: 'Billard-Turnier', type: 'indoor' },
        { text: 'Botanischer Garten Besuch', type: 'outdoor' },
        { text: 'Bach-Picknick', type: 'outdoor' },
        { text: 'Ballonfahrt bei Sonnenuntergang', type: 'outdoor' },
        { text: 'Back-Challenge: Torte kreieren', type: 'indoor' },
        { text: 'Brauerei-Besichtigung', type: 'indoor' },
        { text: 'Burgen-Tour am Wochenende', type: 'outdoor' }
    ],
    'C': [
        { text: 'Cocktail-Kurs zu Hause', type: 'indoor' },
        { text: 'Camping im Garten oder Wald', type: 'outdoor' },
        { text: 'Casino-Nacht (mit Einsatz!)', type: 'indoor' },
        { text: 'Canyoning-Abenteuer', type: 'outdoor' },
        { text: 'Candy-Bar Tasting', type: 'indoor' },
        { text: 'Chillen in der Hängematte', type: 'outdoor' },
        { text: 'Chinesisch kochen lernen', type: 'indoor' },
        { text: 'Comedy-Club Besuch', type: 'indoor' },
        { text: 'Café-Hopping', type: 'both' },
        { text: 'Castle-Besichtigung', type: 'outdoor' }
    ],
    'D': [
        { text: 'Dinner in the Dark', type: 'indoor' },
        { text: 'Dart-Abend', type: 'indoor' },
        { text: 'Dampferfahrt auf dem Fluss', type: 'outdoor' },
        { text: 'Drachensteigen lassen', type: 'outdoor' },
        { text: 'Disco-Rollschuhlaufen', type: 'indoor' },
        { text: 'Draußen schlafen unterm Sternenhimmel', type: 'outdoor' },
        { text: 'Double-Date Spieleabend', type: 'indoor' },
        { text: 'Döner-Test-Tour durch die Stadt', type: 'both' },
        { text: 'DIY-Projekt für die Wohnung', type: 'indoor' },
        { text: 'Draisinen-Tour', type: 'outdoor' }
    ],
    'E': [
        { text: 'Eislaufen gehen', type: 'both' },
        { text: 'Eisessen in der besten Diele', type: 'both' },
        { text: 'E-Bike Tour ins Grüne', type: 'outdoor' },
        { text: 'Erdbeeren pflücken', type: 'outdoor' },
        { text: 'Erotischer Abend mit Überraschung', type: 'indoor' },
        { text: 'Escape Room Challenge', type: 'indoor' },
        { text: 'Einkaufsbummel ohne Budget-Limit', type: 'both' },
        { text: 'Exotisches Früchte-Tasting', type: 'indoor' },
        { text: 'E-Kart fahren', type: 'indoor' },
        { text: 'Entspannung in der Salzgrotte', type: 'indoor' }
    ],
    'F': [
        { text: 'Fondue-Abend (Käse oder Schoko)', type: 'indoor' },
        { text: 'Flohmarkt-Bummel am Morgen', type: 'outdoor' },
        { text: 'Fahrrad-Picknick-Tour', type: 'outdoor' },
        { text: 'Freiluftkino-Besuch', type: 'outdoor' },
        { text: 'Fotografieren im Wald', type: 'outdoor' },
        { text: 'Frühstück im Bett', type: 'indoor' },
        { text: 'Fackelwanderung', type: 'outdoor' },
        { text: 'Fast-Food-Fine-Dining (Zuhause)', type: 'indoor' },
        { text: 'Fähre fahren', type: 'outdoor' },
        { text: 'Fitness-Challenge zu zweit', type: 'both' }
    ],
    'G': [
        { text: 'Grillen im Park', type: 'outdoor' },
        { text: 'Golf-Schnupperkurs', type: 'outdoor' },
        { text: 'Go-Kart Rennen', type: 'indoor' },
        { text: 'Galeriebesuch: Moderne Kunst', type: 'indoor' },
        { text: 'Geocaching im Wald', type: 'outdoor' },
        { text: 'Garten-Projekt starten', type: 'outdoor' },
        { text: 'Gin-Tasting Abend', type: 'indoor' },
        { text: 'Gitarre lernen (oder Ukulele)', type: 'indoor' },
        { text: 'Gokart-Fahren', type: 'indoor' },
        { text: 'Gourmet-Menü kochen', type: 'indoor' }
    ],
    'H': [
        { text: 'Heißluftballonfahrt', type: 'outdoor' },
        { text: 'Hüttenabend mit Kamin', type: 'indoor' },
        { text: 'Hochseilgarten-Parcours', type: 'outdoor' },
        { text: 'Hamam-Besuch für Entspannung', type: 'indoor' },
        { text: 'Helikopter-Rundflug', type: 'outdoor' },
        { text: 'Hunde-Sitting (oder eigenes Gassi)', type: 'outdoor' },
        { text: 'Haus-Party zu zweit (mit DJ)', type: 'indoor' },
        { text: 'Hängematten-Tag im Park', type: 'outdoor' },
        { text: 'Hotel-Übernachtung in eigener Stadt', type: 'indoor' },
        { text: 'Hafenrundfahrt', type: 'outdoor' }
    ],
    'I': [
        { text: 'Indoor-Skydiving', type: 'indoor' },
        { text: 'Iglu-Übernachtung (im Winter)', type: 'outdoor' },
        { text: 'Inlineskaten am See', type: 'outdoor' },
        { text: 'Improvisations-Theater-Kurs', type: 'indoor' },
        { text: 'Insel-Ausflug', type: 'outdoor' },
        { text: 'Indisches Curry kochen', type: 'indoor' },
        { text: 'IT-Detox Tag: Keine Handys', type: 'both' },
        { text: 'Indoor-Minigolf (Schwarzlicht)', type: 'indoor' },
        { text: 'Instagram-Shooting-Tour', type: 'outdoor' },
        { text: 'Iitalienischer Weinabend', type: 'indoor' }
    ],
    'J': [
        { text: 'Jazz-Konzert-Abend', type: 'indoor' },
        { text: 'Jogging-Runde im Wald', type: 'outdoor' },
        { text: 'Jahrmarkt-Besuch', type: 'outdoor' },
        { text: 'Japanisches Restaurant testen', type: 'both' },
        { text: 'Jenga XXL spielen', type: 'both' },
        { text: 'Jonglieren lernen', type: 'both' },
        { text: 'Jollensegeln auf dem See', type: 'outdoor' },
        { text: 'Jeopardy-Abend (selbst erstellt)', type: 'indoor' },
        { text: 'Jet-Ski fahren', type: 'outdoor' },
        { text: 'Joint-Painting (Canvas teilen)', type: 'indoor' }
    ],
    'K': [
        { text: 'Kino-Marathon zu Hause', type: 'indoor' },
        { text: 'Kanufahren auf der Altmühl', type: 'outdoor' },
        { text: 'Kletterwald-Ausflug', type: 'outdoor' },
        { text: 'Kegel-Abend (Oldschool)', type: 'indoor' },
        { text: 'Kochkurs: Pasta selbst machen', type: 'indoor' },
        { text: 'Karaoke-Nacht', type: 'indoor' },
        { text: 'Kabarett-Besuch', type: 'indoor' },
        { text: 'Katamaran-Segeln', type: 'outdoor' },
        { text: 'Kartenspiele-Abend', type: 'indoor' },
        { text: 'Kaffee-Rösterei Besichtigung', type: 'indoor' }
    ],
    'L': [
        { text: 'Laser-Tag Battle', type: 'indoor' },
        { text: 'Lagerfeuer mit Stockbrot', type: 'outdoor' },
        { text: 'Lesung oder Poetry Slam', type: 'indoor' },
        { text: 'Labyrinth-Park erkunden', type: 'outdoor' },
        { text: 'Limonaden-Tasting-Session', type: 'indoor' },
        { text: 'Luftballons steigen lassen', type: 'outdoor' },
        { text: 'Lampignons basteln', type: 'indoor' },
        { text: 'Lange Nacht im Museum', type: 'indoor' },
        { text: 'Live-Musik in einer Bar', type: 'indoor' },
        { text: 'Landpartie mit dem Cabrio', type: 'outdoor' }
    ],
    'M': [
        { text: 'Minigolf-Turnier', type: 'outdoor' },
        { text: 'Museum für Naturkunde', type: 'indoor' },
        { text: 'Massage-Workshop zu Hause', type: 'indoor' },
        { text: 'Musical-Besuch', type: 'indoor' },
        { text: 'Malkurs (Bob Ross Style)', type: 'indoor' },
        { text: 'Mondschein-Picknick', type: 'outdoor' },
        { text: 'Marktplatz-Bummel', type: 'outdoor' },
        { text: 'Metropole erkunden (Städtetrip)', type: 'outdoor' },
        { text: 'Mountainbike-Tour', type: 'outdoor' },
        { text: 'Mittelalter-Markt Besuch', type: 'outdoor' }
    ],
    'N': [
        { text: 'Nachtwanderung im Wald', type: 'outdoor' },
        { text: 'Natur-Pur im Nationalpark', type: 'outdoor' },
        { text: 'Netflix \u0026 Chill mit Gourmet-Popcorn', type: 'indoor' },
        { text: 'Night-Shopping Event', type: 'indoor' },
        { text: 'Nordic-Walking-Tour', type: 'outdoor' },
        { text: 'Nasch-Tour: Beste Pralinen finden', type: 'both' },
        { text: 'Nonsens-Gespräche am Feuer', type: 'outdoor' },
        { text: 'Nach Sterne Ausschau halten', type: 'outdoor' },
        { text: 'Ninja-Warrior Parcours (Halle)', type: 'indoor' },
        { text: 'Neues Hobby ausprobieren', type: 'both' }
    ],
    'O': [
        { text: 'Opernball oder Opern-Besuch', type: 'indoor' },
        { text: 'Oldtimer-Tour übers Land', type: 'outdoor' },
        { text: 'Orient-Essen im Restaurant', type: 'indoor' },
        { text: 'Obstpflücken auf der Plantage', type: 'outdoor' },
        { text: 'Orgel-Konzert im Dom', type: 'indoor' },
        { text: 'Outfittery: Gegenseitig einkleiden', type: 'both' },
        { text: 'Observation: Leute beobachten im Park', type: 'outdoor' },
        { text: 'Online-Escape Game spielen', type: 'indoor' },
        { text: 'Original Pizza backen', type: 'indoor' },
        { text: 'Outdoor-Workout im Park', type: 'outdoor' }
    ],
    'P': [
        { text: 'Picknick im Sonnenuntergang', type: 'outdoor' },
        { text: 'Planetarium: Sternenhimmel-Show', type: 'indoor' },
        { text: 'Paintball-Session', type: 'both' },
        { text: 'Poker-Nacht (mit Strip-Einsatz?)', type: 'indoor' },
        { text: 'Paragliding-Tandemsprung', type: 'outdoor' },
        { text: 'Puzzeln der 1000 Teile', type: 'indoor' },
        { text: 'Pferdereiten am Strand', type: 'outdoor' },
        { text: 'Private Wine-Tasting', type: 'indoor' },
        { text: 'Paddeln auf dem See', type: 'outdoor' },
        { text: 'Palmengarten-Spaziergang', type: 'both' }
    ],
    'Q': [
        { text: 'Qualitätszeit-Gutscheinbuch basteln', type: 'indoor' },
        { text: 'Quizabend: Wer weiß mehr über Partner?', type: 'indoor' },
        { text: 'Quiche-Back-Challenge', type: 'indoor' },
        { text: 'Quadtour durchs Gelände', type: 'outdoor' },
        { text: 'Quiet-Date: Gemeinsam lesen', type: 'indoor' },
        { text: 'Quatschen bis zum Sonnenaufgang', type: 'both' },
        { text: 'Quellbesuch im Naturpark', type: 'outdoor' },
        { text: 'Quirky-Kunst-Projekt', type: 'indoor' },
        { text: 'Quarantäne-Kit für Kuschelstunden', type: 'indoor' },
        { text: 'Q-Scrabble-Match', type: 'indoor' }
    ],
    'R': [
        { text: 'Radtour zum nächsten See', type: 'outdoor' },
        { text: 'Rooftop-Bar-Besuch', type: 'both' },
        { text: 'Roadtrip ohne Ziel', type: 'outdoor' },
        { text: 'Rudern am Stadtweiher', type: 'outdoor' },
        { text: 'Restaurant: Neu-Eröffnung testen', type: 'both' },
        { text: 'Reiten lernen für einen Tag', type: 'outdoor' },
        { text: 'Rätsel-Abend zu Hause', type: 'indoor' },
        { text: 'Rollschuh-Laufen (Retro Style)', type: 'both' },
        { text: 'Romantisches Bad für Zwei', type: 'indoor' },
        { text: 'Religions-Event: Tempel/Kirche besuchen', type: 'both' }
    ],
    'S': [
        { text: 'Sauna \u0026 Wellness-Tag', type: 'indoor' },
        { text: 'Stand-Up Paddling (SUP)', type: 'outdoor' },
        { text: 'Stadtführung: Die eigene Stadt neu entdecken', type: 'outdoor' },
        { text: 'Schlittschuhlaufen (Winter)', type: 'both' },
        { text: 'Sushi-Kurs für Einsteiger', type: 'indoor' },
        { text: 'Sterne beobachten im Park', type: 'outdoor' },
        { text: 'Spiele-Abend: Klassiker rauskramen', type: 'indoor' },
        { text: 'Sonnenaufgang auf einem Hügel', type: 'outdoor' },
        { text: 'Schwimmen im Freibad', type: 'outdoor' },
        { text: 'Segeln lernen', type: 'outdoor' }
    ],
    'T': [
        { text: 'Theater-Besuch', type: 'indoor' },
        { text: 'Therme \u0026 Sauna', type: 'indoor' },
        { text: 'Tanzkurs: Salsa oder Walzer', type: 'indoor' },
        { text: 'Tennis-Match', type: 'both' },
        { text: 'Tierpark/Zoo-Tag', type: 'outdoor' },
        { text: 'Trödelmarkt-Rallye', type: 'outdoor' },
        { text: 'Tauchkurs (Schnupper)', type: 'indoor' },
        { text: 'Tischtennis-Turnier', type: 'both' },
        { text: 'Tee-Verkostung', type: 'indoor' },
        { text: 'Trampolinhalle-Action', type: 'indoor' }
    ],
    'U': [
        { text: 'U-Bahn-Rallye durch die Stadt', type: 'indoor' },
        { text: 'Urlaub am Wochenende (Überraschung)', type: 'outdoor' },
        { text: 'Unterwasser-Zoo (Aquarium)', type: 'indoor' },
        { text: 'Utopia: Gemeinsame Zukunft planen', type: 'indoor' },
        { text: 'Urwald-Trip im botanischen Garten', type: 'both' },
        { text: 'U-Boot-Fahrt (falls möglich)', type: 'both' },
        { text: 'Ukulele-Duo-Konzert zu Hause', type: 'indoor' },
        { text: 'Unterhaltung: Comedy-Show', type: 'indoor' },
        { text: 'Urban Gardening Session', type: 'outdoor' },
        { text: 'Upcycling-Projekt gemeinsam', type: 'both' }
    ],
    'V': [
        { text: 'Varieté-Besuch', type: 'indoor' },
        { text: 'Vernissage besuchen', type: 'indoor' },
        { text: 'Video-Abend: Alte Filme gucken', type: 'indoor' },
        { text: 'Volleyball im Park', type: 'outdoor' },
        { text: 'Verkostung: Wein oder Käse', type: 'indoor' },
        { text: 'Vogelpark erkunden', type: 'outdoor' },
        { text: 'Verschönere die Wohnung (Action)', type: 'indoor' },
        { text: 'Virtual Reality Arena', type: 'indoor' },
        { text: 'Vesper-Picknick am Berg', type: 'outdoor' },
        { text: 'Vintage-Shopping-Trip', type: 'both' }
    ],
    'W': [
        { text: 'Wandern im Mittelgebirge', type: 'outdoor' },
        { text: 'Wellness-Massage-Tag', type: 'indoor' },
        { text: 'Weinprobe beim Winzer', type: 'both' },
        { text: 'Wasserski-Anlage testen', type: 'outdoor' },
        { text: 'Wildpark-Wanderung', type: 'outdoor' },
        { text: 'Wrestling-Show besuchen', type: 'indoor' },
        { text: 'Writing-Session: Briefe an die Zukunft', type: 'indoor' },
        { text: 'Windsurfen probieren', type: 'outdoor' },
        { text: 'Wohnmobil-Wochenende', type: 'outdoor' },
        { text: 'Whisky-Tasting', type: 'indoor' }
    ],
    'X': [
        { text: 'XXL-Pizza Essen gehen', type: 'both' },
        { text: 'Xbox-Challenge-Abend', type: 'indoor' },
        { text: 'Xylofon-Unterricht (Schnupper)', type: 'indoor' },
        { text: 'X-Wochenend-Trip (Überraschung)', type: 'outdoor' },
        { text: 'Xmas-Markt-Hopping (Saison)', type: 'outdoor' },
        { text: 'X-Faktor: Grusel-Abend', type: 'indoor' },
        { text: 'XXL-Kuscheldecken-Tag', type: 'indoor' },
        { text: 'X-beliebigen Ort auf Karte wählen und hinfahren', type: 'outdoor' },
        { text: 'X-Ray: Was bewegt uns gerade? (Talk)', type: 'indoor' },
        { text: 'Exklusives Erlebnis buchen (Fallschirm...)', type: 'outdoor' }
    ],
    'Y': [
        { text: 'Yoga im Park', type: 'outdoor' },
        { text: 'Yachting-Trip (Segeln)', type: 'outdoor' },
        { text: 'YouTube-Karaoke-Nacht', type: 'indoor' },
        { text: 'Yankee-Candle-Shopping', type: 'indoor' },
        { text: 'Yogi-Tee Zeremonie', type: 'indoor' },
        { text: 'Yam-Essen (exotisch)', type: 'both' },
        { text: 'Yogurt-Ice-Cream-Bar', type: 'both' },
        { text: 'Y-Wanderung (Y-förmige Route)', type: 'outdoor' },
        { text: 'Yin \u0026 Yang Abend (Balance)', type: 'indoor' },
        { text: 'Yuppie-Date: Schick essen gehen', type: 'both' }
    ],
    'Z': [
        { text: 'Zoo-Besuch', type: 'outdoor' },
        { text: 'Zelten am See', type: 'outdoor' },
        { text: 'Zirkus-Besuch', type: 'both' },
        { text: 'Zumba-Kurs für Zwei', type: 'indoor' },
        { text: 'Zaubershow-Ticket', type: 'indoor' },
        { text: 'Zukunfts-Planung (Reiseziele)', type: 'indoor' },
        { text: 'Zirkus-Workshop (Jonglieren)', type: 'indoor' },
        { text: 'Zeichenkurs für Porträts', type: 'indoor' },
        { text: 'Zitadellen-Besuch', type: 'outdoor' },
        { text: 'Zweirad-Tour (Motorrad/Roller)', type: 'outdoor' }
    ],
    'DEFAULT': [
        { text: 'Einfach mal nichts tun', type: 'indoor' },
        { text: 'Überraschungs-Date', type: 'both' },
        { text: 'Leute beobachten im Café', type: 'both' },
        { text: 'Gemeinsames Bad', type: 'indoor' },
        { text: 'Frühstücken gehen', type: 'both' }
    ]
};
